### ISSUE TITLE
User Login

### ISSUE THREAD

**Issue by anmolmalhotra97** [anmolmalhotra97/ExamPortalBackend#14]
- [x] #16
- [x] #17

**Comment by AyushKatiyar972194** [comment]
Doing great

**Comment by anmolmalhotra97** [comment]
### **Logged In User Dashboard**

![Logged In User Dashboard](https://user-images.githubusercontent.com/26005821/209939300-30a348f3-d07f-42c1-9e42-2ee783923808.png)
